GET http://127.0.0.1:5000/
HTTP 200

GET http://127.0.0.1:5000/assets/bootstrap/css/bootstrap.min.css
HTTP 200

GET http://127.0.0.1:5000/assets/css/styles.min.css
HTTP 200

GET http://127.0.0.1:5000/favicon.png
HTTP 200

GET http://127.0.0.1:5000/assets/spotify.webp
HTTP 200

GET http://127.0.0.1:5000/assets/spotify.png
HTTP 200

GET http://127.0.0.1:5000/assets/background.webp
HTTP 200

GET http://127.0.0.1:5000/assets/nathan3dprinting.webp
HTTP 200