name: Check Code Quality
run-name: Ruff CI
on:
  push:

jobs:
  RuffCheck:
    runs-on: [ubuntu-latest, amd]
    steps:
      - uses: actions/checkout@v2
      - uses: https://github.com/astral-sh/ruff-action@v3