[METADATA]
modified = 2024-07-02T00:00:00.000Z
expires = 2050-07-02T00:00:00.000Z

[[ACCOUNTS]]
address = "rKzdnYvwDyeki5VCgMwjuofjBjAbg3DJnB"
desc = "Nathan.Woodburn/ (Twitter: @nathanwoodburn)"

[[PRINCIPALS]]
name = "Nathan Woodburn"
email = "xrp@nathan.woodburn.au"
social_1 = "https://nathan.woodburn.au"